# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherFull' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.2'
pod 'AlamofireImage', '~> 3.2'
pod 'RealmSwift', '~> 2.1'
pod 'SwiftyJSON', '~> 3.1'

  # Pods for WeatherFull

end
