# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FlowersOnline' do

pod 'GBInfiniteScrollView', '~> 1.6'
pod 'SCLAlertView-Objective-C'
pod "AFNetworking", "~> 2.0"
pod 'Motis', '~>1.3.0'
pod 'SDWebImage', '~>3.7'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod "MagicalRecord"
pod 'MONActivityIndicatorView'

end
