# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FlowersOnline' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
'GBInfiniteScrollView' '~> 1.6'


  # Pods for FlowersOnline

end
