# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Weddup' do
pod "AFNetworking", "~> 2.0"
pod 'Motis', '~>1.3.0'
pod 'SDWebImage', '~>3.7'
pod "youtube-ios-player-helper", "~> 0.1.4"
pod 'SCLAlertView-Objective-C'
end

