# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PsychologistIOS' do

pod "AKPickerView"

end

target 'PsychologistIOSTests' do

end

target 'PsychologistIOSUITests' do

end

