# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Kinopro365' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Kinopro365


pod 'MMDrawerController', '~> 0.5.7'
pod 'NYAlertViewController', '~> 1.3'
pod "AFNetworking", "~> 2.0"
pod 'Motis', '~>1.3.0'
pod 'SDWebImage', '~>3.7'
pod "MagicalRecord"

end
